name: Dependency Updates

on:
  schedule:
    - cron: '0 8 * * 1'  # Weekly on Monday at 8 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pip-tools
      run: pip install pip-tools

    - name: Update requirements
      run: |
        pip-compile --upgrade requirements.in --output-file requirements.txt || echo "No requirements.in found"
        pip-compile --upgrade requirements-test.in --output-file requirements-test.txt || echo "No requirements-test.in found"

    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check --json --output safety-check.json || true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated dependency updates'
        body: |
          Automated dependency updates generated by GitHub Actions.
          
          Please review the changes and run tests before merging.
        branch: automated-dependency-updates
        delete-branch: true 